/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer_pac;
import GUI.*;
import database.*;
import Classes.*;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author heman
 */
public class CustomerPanel extends javax.swing.JFrame {

    /**
     * Creates new form CustomerPanel
     */
    CustomerInfo user = new CustomerInfo();
     
    CustomerDb db = new CustomerDb();
    ResultSet result = null;
    
    public CustomerPanel() {
            initComponents();
            setTitle("Customer Details");
            populateWithCustomerData();
            
    }
    public void rowCount(){
        DefaultTableModel model= (DefaultTableModel)table_customer.getModel();
        try{
            model.setRowCount(0);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void populateWithCustomerData()
    {
        ResultSet rs = Select.getData("select * from customer");
        DefaultTableModel model= (DefaultTableModel)table_customer.getModel();
        try{
            while(rs.next()){
                model.addRow(new Object[] {rs.getString(1),rs.getString(2),rs.getString(5),rs.getString(4),rs.getString(3),rs.getString(6),rs.getString(8),rs.getString(7)});
            }
            rs.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_cname = new javax.swing.JTextField();
        tf_cnationality = new javax.swing.JTextField();
        tf_cphone = new javax.swing.JTextField();
        tf_cemail = new javax.swing.JTextField();
        tf_caddress = new javax.swing.JTextField();
        btn_editcustomer = new javax.swing.JButton();
        btn_deletecustomer = new javax.swing.JButton();
        btn_addcustomer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_customer = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_caadhar = new javax.swing.JTextField();
        btn_searchcustomer = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_cgender = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setText("Customer Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mobile Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        tf_cname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tf_cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 241, -1));

        tf_cnationality.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tf_cnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 241, -1));

        tf_cphone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tf_cphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 241, -1));

        tf_cemail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tf_cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 241, -1));

        tf_caddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tf_caddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 241, 79));

        btn_editcustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_editcustomer.setForeground(new java.awt.Color(255, 0, 0));
        btn_editcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btn_editcustomer.setText("Edit");
        btn_editcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 160, 50));

        btn_deletecustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_deletecustomer.setForeground(new java.awt.Color(255, 0, 0));
        btn_deletecustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_deletecustomer.setText("  Delete");
        btn_deletecustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletecustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_deletecustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 620, 150, 50));

        btn_addcustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_addcustomer.setForeground(new java.awt.Color(255, 0, 0));
        btn_addcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_addcustomer.setText("Add");
        btn_addcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_addcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 160, 50));

        table_customer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        table_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Gender", "Nationality", "Phone no", "Email", "Address", "Aadhar number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_customerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_customerMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_customer);
        if (table_customer.getColumnModel().getColumnCount() > 0) {
            table_customer.getColumnModel().getColumn(0).setResizable(false);
            table_customer.getColumnModel().getColumn(1).setResizable(false);
            table_customer.getColumnModel().getColumn(2).setResizable(false);
            table_customer.getColumnModel().getColumn(3).setResizable(false);
            table_customer.getColumnModel().getColumn(4).setResizable(false);
            table_customer.getColumnModel().getColumn(5).setResizable(false);
            table_customer.getColumnModel().getColumn(6).setResizable(false);
            table_customer.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 770, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, -1, -1));

        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 0, 0));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset.png"))); // NOI18N
        btn_reset.setText(" Reset Fields");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 160, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Aadhar no");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        tf_caadhar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(tf_caadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 240, -1));

        btn_searchcustomer.setBackground(new java.awt.Color(255, 239, 225));
        btn_searchcustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_searchcustomer.setForeground(new java.awt.Color(255, 0, 0));
        btn_searchcustomer.setText("Search/Sort Customers");
        btn_searchcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_searchcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 239, 225));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Customer CheckIn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        tf_cgender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_cgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cgenderActionPerformed(evt);
            }
        });
        getContentPane().add(tf_cgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 240, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 30, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IMBAC.jpg"))); // NOI18N
        jLabel8.setText(" ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Do You really want to close this application?", "select",
                JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new home().setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void table_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_customerMouseClicked
        user = new CustomerInfo();
        DefaultTableModel model= (DefaultTableModel)table_customer.getModel();
        int row = table_customer.getSelectedRow();
        displayToTextField(row);
        btn_addcustomer.setEnabled(false);
        btn_editcustomer.setEnabled(true);
        btn_deletecustomer.setEnabled(true);
    }//GEN-LAST:event_table_customerMouseClicked

    private void table_customerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_customerMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_table_customerMousePressed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        emptyField();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_searchcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchcustomerActionPerformed
        new CustomerSearchSort().setVisible(true);
        
    }//GEN-LAST:event_btn_searchcustomerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_cgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cgenderActionPerformed

    
private void btn_addcustomerActionPerformed(java.awt.event.ActionEvent evt){
    ObjectCreation();
   
     db.insertCustomer(user);
     // ObjectCreation1();
     db.insertLog(user);
//     String query = "insert into customer(id, name,mobileNumber,nationality,gender,email,aadhar,address) values('"+Integer.parseInt(tokens1.get(0))
//     +"','"+tokens1.get(1)+"','"+tokens1.get(2)+"','"+tokens1.get(3)+"','"+tokens1.get(4)+"','"+tokens1.get(5)+"','"+tokens1.get(6)+"')";
//     initial_csv("insert",query);

     rowCount();
    populateWithCustomerData();
    CustomerInfo cp = new CustomerInfo();
    cp.CustomerDetailsPrinter(user);
    emptyField();
}

private void emptyField()
    {
        btn_addcustomer.setEnabled(true);
        btn_editcustomer.setEnabled(false);
        btn_deletecustomer.setEnabled(false);
        
        user = new CustomerInfo();
       jTextField1.setText("");
        tf_caddress.setText("");
        tf_cemail.setText("");
        tf_cgender.setText("");
        tf_cnationality.setText("");
        tf_cname.setText("");
        tf_cphone.setText("");
        tf_caadhar.setText("");
        table_customer.clearSelection();
    }                                       

    private void btn_editcustomerActionPerformed(java.awt.event.ActionEvent evt) {                                                 
       //  ObjectCreation1();
       ObjectCreation();
        db.updateCustomer(user);
       
        db.updatelog(user);
        rowCount();
        populateWithCustomerData();
        emptyField();
    }                                                

    private void btn_deletecustomerActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        int row  = table_customer.getSelectedRow();
        String selectedUserId = (String) table_customer.getModel().getValueAt(row, 0);
        try {
            db.deleteCustomer(selectedUserId);
            db.deletelog(selectedUserId);
        } catch (SQLException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        rowCount();
        populateWithCustomerData(); 
        emptyField();
    }
    private void displayToTextField(int row){   
        DefaultTableModel model= (DefaultTableModel)table_customer.getModel();
    row = table_customer.getSelectedRow();
    jTextField1.setText(table_customer.getModel().getValueAt(row, 0).toString());
    tf_cname.setText(table_customer.getModel().getValueAt(row, 1).toString());
    tf_cgender.setText(table_customer.getModel().getValueAt(row, 2).toString());
    tf_cnationality.setText(table_customer.getModel().getValueAt(row, 3).toString());
    tf_cphone.setText(table_customer.getModel().getValueAt(row, 4).toString());
    tf_cemail.setText(table_customer.getModel().getValueAt(row, 5).toString());
    tf_caddress.setText(table_customer.getModel().getValueAt(row, 6).toString());
    tf_caadhar.setText(table_customer.getModel().getValueAt(row, 7).toString());
   }
    
   
    private void ObjectCreation()
    {   
 
        user = new CustomerInfo();
        user.setId(Integer.parseInt(jTextField1.getText()));
        user.setName(tf_cname.getText());
        user.setAddress(tf_caddress.getText());
        user.setMobileNumber(tf_cphone.getText());
        user.setEmail(tf_cemail.getText());
        user.setGender(tf_cgender.getText());
        user.setNationality(tf_cnationality.getText());
        user.setAadhar(tf_caadhar.getText());
        
        
    }
private void ObjectCreation1()
    {   
 
        user = new CustomerInfo();
        user.setId(user.returnid(tf_caadhar.getText()));
        
        user.setName(tf_cname.getText());
        user.setAddress(tf_caddress.getText());
        user.setMobileNumber(tf_cphone.getText());
        user.setEmail(tf_cemail.getText());
        user.setGender(tf_cgender.getText());
        user.setNationality(tf_cnationality.getText());
        user.setAadhar(tf_caadhar.getText());
        
        
    }

private void tf_phoneKeyTyped(java.awt.event.KeyEvent evt) {                                  
         char c = evt.getKeyChar();
        
        if(!(Character.isDigit(c) || c== KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE ))
        {
            evt.consume();
        }
    }                                 


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addcustomer;
    private javax.swing.JButton btn_deletecustomer;
    private javax.swing.JButton btn_editcustomer;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_searchcustomer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable table_customer;
    private javax.swing.JTextField tf_caadhar;
    private javax.swing.JTextField tf_caddress;
    private javax.swing.JTextField tf_cemail;
    private javax.swing.JTextField tf_cgender;
    private javax.swing.JTextField tf_cname;
    private javax.swing.JTextField tf_cnationality;
    private javax.swing.JTextField tf_cphone;
    // End of variables declaration//GEN-END:variables
}
